######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 8 16:48:45 2010
######################################################################

TEMPLATE = lib
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += designer plugin release

# Input
HEADERS += RotatedLabelPlugin.h ../rotatedlabel.h
SOURCES += RotatedLabelPlugin.cpp ../rotatedlabel.cpp
RESOURCES += text.qrc

DESTDIR = /usr/lib/qt4/plugins/designer
