######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 17 12:27:41 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += panelReg.h
FORMS += panelReg.ui
SOURCES += panelReg.cpp
RESOURCES += panelReg.qrc
